### ISSUE TITLE
Add a license file to repository

### ISSUE THREAD

**Issue by mithro** [gregdavill/DiVA-firmware#7]
Could you please?

**Comment by gregdavill** [comment]
Thanks, this is always something I forget to do.

Added in https://github.com/gregdavill/DiVA-firmware/commit/facdbd6dde9f4980d60b4b34ffe66a075ad1efcb

**Comment by mithro** [comment]
Looks like you might have added a licence file, rather than a license file?

**Comment by gregdavill** [comment]
Fixed in 9913a42403029dc0389e9d44ab0898c51c93ce5b
